### ISSUE TITLE
Allow .gitignore files to update during self-update 

### ISSUE THREAD

**Issue by biswaupreti** [Exove/local-docker#162]
## Overview
.gitignore are never updated while updating local-docker using self-update script. Eg: db_dumps/.gitignore was updated during the release version 1.3.0 but the projects started with older versions of local-docker still have initial version of db_dumps/.gitignore file that allows git to track single database dumps such as, `db-backup--*.sql*`. 

## Proposed solution
This is possibly due to the reason that .gitignore are excluded from the list defined here:  https://github.com/Exove/local-docker/blob/156a9727cb54d8dab1a498e69088c00277a40684/docker/scripts/self-update.sh#L55 
IMO allowing it to update can be one possible fix.

**Comment by rpsu** [comment]
`.gitignore` file is intentionally NOT included in the self-update, but the `.gitignore.example` is, with instructions to review the updates in the example file. 

This is done in order to not overwrite casually project's .gitignore and the project specific changes in them. The same goes with `.env.local.example`.
