### ISSUE TITLE
Install Drush launcher, remove hardcoded drush alias

### ISSUE THREAD

**Issue by rpsu** [Exove/local-docker#18]
https://github.com/drush-ops/drush-launcher

Optionally do the same for Drupal console.

**Comment by rpsu** [comment]
https://github.com/Exove/local-docker-generic haed Drush launcher already there

**Comment by hirvinen** [comment]
I think it may be a good idea to postpone this until we can expect people to use a drush version where https://github.com/drush-ops/drush/issues/3595 , or verify that the issue does not affect the local-docker stack. We have this issue affecting at least one vagrant-based local, and a possibly related issue that at least in some cases xdebug on that local did not work when drush-launcher was used instead of directly invoking drush.

**Comment by rpsu** [comment]
Fixed by #203
